version: "3.8"
services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    ports:
      - 80:8096
    volumes:
      - /media/jellyfin/cache:/cache
      - /media/jellyfin/config:/config
      - /media:/media
    deploy:
      replicas: 1
  transmission:
    image: linuxserver/transmission:latest
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /media/transmission/config:/config
      - /media/downloads:/downloads
      - /media/watch:/watch
